name = "DASVader"
uuid = "59bca59c-d90f-4a35-94f3-551978ff0700"
authors = ["Mariano Arnaiz <mararnai@ipgp.fr>"]
version = "0.1.0"

[deps]
GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Seis = "dd80f4d8-c2f6-58bd-9bd3-4635f134261d"
FillArrays = "1a297f60-69ca-5386-bcde-b61e274b549b"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
FourierAnalysis = "e7e9c730-dc46-11e9-3633-f1ab55cc17e1"
DSP = "717857b8-e6f2-59f4-9121-6e50c889abd2"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
MakieThemes = "e296ed71-da82-5faf-88ab-0034a9761098"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
Observables = "510215fc-4207-5dde-b226-833fc4488ee2"
ScatteredInterpolation = "7f1e8635-cd0d-4e6b-86ab-02fef676d4e3"
RollingFunctions = "b0e4dd01"

